### ISSUE TITLE
Index out bound issue on converting some hash hex

### ISSUE THREAD

**Issue by legendz3** [piranout/Funcular.IdGenerators#3]
Getting index out of bound issues in the Convert method in BaseConverter. For hash 2D-17-54-7F-A8, the following exception was thrown, value was set to -528472 at the end of the while loop in the Convert method:

IndexOutOfRangeException

Index was outside the bounds of the array.

C:\Users\p747527\Documents\GitHub\Funcular.IdGenerators\Base36\Base36IdGenerator.cs in .ctor at line 132:13

Void .ctor(Int32, Int32, Int32, System.String, System.String, Int32[])
C:\Users\p747527\Documents\GitHub\Funcular.IdGenerators\Base36\Base36IdGenerator.cs in ComputeHostHash at line 250:13

System.String ComputeHostHash()
C:\Users\p747527\Documents\GitHub\Funcular.IdGenerators\BaseConversion\Base36Converter.cs in FromHex at line 71:13

System.String FromHex(System.String)
C:\Users\p747527\Documents\GitHub\Funcular.IdGenerators\BaseConversion\BaseConverter.cs in Convert at line 80:17

System.String Convert(System.String, Int32, Int32)

I believe it's the same issue as https://github.com/piranout/Funcular.IdGenerators/issues/1. But this hexHash was calculated by the IdGenerator and not a value passed in straight to the Convert method.

**Comment by piranout** [comment]
Thanks, I will take a look.

**Comment by piranout** [comment]
Can you give me the values that were passed to the constructor, and the name of the machine being used? (That is significant to the ComputeHostHash function.)

**Comment by legendz3** [comment]
The values passed in was 
`var generator = new Base36IdGenerator(
                numTimestampCharacters: 12,
                numServerCharacters: 6,
                numRandomCharacters: 7,
                reservedValue: "",
                delimiter: "-",
                delimiterPositions: new[] { 20, 15, 10, 5 });`

The machine name is RD00155DC193F9 (Azure web role)

**Comment by piranout** [comment]
Okay, I have a fix, but it has a consequence: Server hashes will not match values from previous versions. This is a real bug; `BitConverter.ToString(sha1.ComputeHash(Encoding.UTF8.GetBytes(hostname)` includes dashes in the hex string output, and I did not account for this in the base conversion from hex to base 36. 

I will commit the fix to github today, but since this might be a breaking change to users who are relying on the server hash for tracing, I'll not publish it to NuGet.org immediately. (I have to think about how to communicate the potentially breaking change to those users so as not to surprise them.)

**Comment by piranout** [comment]
I have pushed a fix for this to GitHub, and I added a unit test with your specific server name (I will add others if this is encountered again). Remember that host hashes will now differ from those produced by previous versions. If nobody has issues, I'll push this fix out to NuGet in a few days.

**Comment by piranout** [comment]
This has been pushed to NuGet.
